config/routes.rb
Rails.application.routes.draw do

  devise_for :admin_users, ActiveAdmin::Devise.config
  ActiveAdmin.routes(self)
  root 'home#index'

  resources :categories, only: [:show]
  resources :products, only: [:index, :show]
  resources :offers, only: [:index]
  resources :about, only: [:index]
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/admin_user.rb
class AdminUser < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, 
         :recoverable, :rememberable, :validatable
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/category.rb
class Category < ApplicationRecord
  mount_uploader :image, ImageUploader
  has_many :products

  accepts_nested_attributes_for :products, allow_destroy: true

  # scopes
  scope :filter_by_style, -> (tag) { joins(:tags).where(tags: {name: tag})}
  default_scope { eager_load(:products) }
end

app/models/city.rb
class City < ApplicationRecord
  has_many :products
end

app/models/product.rb
class Product < ApplicationRecord
    mount_uploader :picture_1, ImageUploader
    mount_uploader :picture_2, ImageUploader
    mount_uploader :picture_3, ImageUploader
    belongs_to :category
    belongs_to :provider
    belongs_to :city
end

app/models/provider.rb
class Provider < ApplicationRecord
  has_many :products
end

app/controllers/about_controller.rb
class AboutController < ApplicationController; end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # protect_from_forgery with: :exception
  # before_action :all_categories

  # def all_categories
  #   @categories = Category.all()
  # end
end

app/controllers/categories_controller.rb
class CategoriesController < ApplicationController
  include Pagy::Backend
  before_action :set_category, only: %i[show]
  before_action :all_categories

  def index
    @pagy, @products = pagy(Product.all, page: params[:page], items: 8)
  end

  def show
    @pagy, @products = pagy(Product.where(category_id: params[:id]), page: params[:page], items: 12)
  end

  private

  def set_category
    @category = Category.find(params[:id])
  end

  def all_categories
    @categories = Category.all()
  end
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  include Pagy::Backend
  protect_from_forgery with: :exception

  before_action :set_product, only: %i[show]
  before_action :all_categories

  def index
    @filter = params[:filter]
    @pagy, @products = @filter.nil? ? pagy(Product.where(available: true), page: params[:page], items: 4) : pagy(Product.where(available: true).filter_by_style(@filter), page: params[:page], items: 4)
  end
  
  private
  
  def set_product
    @product = Product.find(params[:id])
  end

  def all_categories
    @categories = Category.all()
  end
end

app/controllers/offers_controller.rb
class OffersController < ApplicationController
  include Pagy::Backend
  protect_from_forgery with: :exception
  before_action :all_categories

  def index
    @filter = params[:filter]
    @pagy, @products = @filter.nil? ? pagy(Product.where(available: true, offer: true), page: params[:page], items: 12) : pagy(Product.where(available: true, offer: true).filter_by_style(@filter), page: params[:page], items: 12)
  end

  private

  def all_categories
    @categories = Category.all()
  end
end

app/controllers/products_controller.rb
class ProductsController < ApplicationController
  include Pagy::Backend
  before_action :set_product, only: %i[show]
  before_action :all_categories
  
  def index
    @pagy, @products = pagy(Product.all, page: params[:page], items: 12)
  end
  
  private

  def set_product
    @product = Product.find(params[:id])
  end

  def all_categories
    @categories = Category.all()
  end
end

app/helpers/about_helper.rb
module AboutHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/categories_helper.rb
module CategoriesHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/offers_helper.rb
module OffersHelper
  include Pagy::Frontend
  require 'pagy/extras/bootstrap'
end

app/helpers/products_helper.rb
module ProductsHelper
  include Pagy::Frontend
  require 'pagy/extras/bootstrap'
  
  def set_images(picture1, picture2, picture3)
		images = Array.new
		images.push(picture1) unless picture1.nil? || picture1.blank?
		images.push(picture2) unless picture2.nil? || picture2.blank?
		images.push(picture3) unless picture3.nil? || picture3.blank?
		return images
  end
  
end

app/views/about/index.html.erb
<!-- Header -->
<%= render "commun/header" %>

<!-- Title Page -->
<section  class="bg-title-page p-t-40 p-b-50 flex-col-c-m"
          style="background: linear-gradient(rgba(0,0,0,0.5), rgba(0,0,0,0.7)), url(images/heading-pages-06.jpg);
                background-repeat: no-repeat;
                background-size: cover;
                background-position: center center;
                color: #fff;
                text-align: center;">
  <div class="bo13 p-l-29 m-l-9 p-b-10">
    <h2 class="l-text2 t-center">
      Es mejor hecho en Ecuador.
    </h2>

    <span class="s-text7" style="color: white">
      - Tienda Nativa
    </span>
  </div>
</section>

<!-- content page -->
<section class="bgwhite p-t-66 p-b-38">
  <div class="container">
    <div class="row">
      <div class="col-md-4 p-b-30">
        <div class="hov-img-zoom">
          <img src="images/banner-14.jpg" alt="IMG-ABOUT">
        </div>
      </div>

      <div class="col-md-8 p-b-30">
        <h3 class="m-text26 p-t-15 p-b-16">
          Misión.
        </h3>

        <p class="p-b-28">
          Proyectar a nivel nacional los productos, desarrollados en los rincones de ecuador, con materia prima ecuatoriana, socializando, vendiendo y distribuyendo a nivel nacional, para así ampliar y potenciar su calidad, sabor y material.
        </p>

        <h3 class="m-text26 p-t-15 p-b-16">
          Visión.
        </h3>

        <p class="p-b-28">
          Ser reconocido como la plataforma que permita la trascendencia de los sabores , colores y forma en el resto del país, apalancando el desarrollo del productor interno.
        </p>

        <h3 class="m-text26 p-t-15 p-b-16">
          Quienes Somos.
        </h3>

        <p class="p-b-28">
          Somos unos emprendedores que creemos en la calidad, sabor, durabilidad, fortaleza de los productos ecuatorianos, que se ha propuesto unirlos en una plataforma digital y demostrar al resto de las provincias que tenemos productos internos que pueden ser mejor que sus pares extranjeros, cediendo el espacio como plaza Tienda Nativa, donde el productor pueda mostrar sus productos , venderlos y distribuirlos y así mejorar la proyección y cobertura de sus productos.
        </p>
        <p class="p-b-28">
          El proyecto nace de 2 personas conocidas que se encuentra una en Sierra y la otra en la Costa Ecuatoriana, e intercambian las bondades de ambas regiones.
        </p>

        <div class="bo13 p-l-29 m-l-9 p-b-10">
          <p class="p-b-11">
            La creatividad es solo conectar cosas. Cuando les preguntas a las personas creativas cómo hicieron algo, se sienten un poco culpables porque realmente no lo hicieron, solo vieron algo. Les pareció obvio después de un rato.
          </p>

          <span class="s-text7">
            - Steve Job’s
          </span>
        </div>
      </div>
    </div>
  </div>
</section>

<!-- Footer -->
<%= render "commun/footer"%>

app/views/categories/show.html.erb
<!-- Header -->
<%= render "commun/header" %>

<!-- Title Page -->
<section class="bg-title-page p-t-50 p-b-40 flex-col-c-m"
  style="background: linear-gradient(rgba(0,0,0,0.5), rgba(0,0,0,0.7)), url(images/heading-pages-02.jpg);
        background-repeat: no-repeat;
        background-size: cover;
        background-position: center center;
        color: #fff;
        text-align: center;">

  <h2 class="l-text2 t-center">
    Producto en Ecuador.
  </h2>
  <p class="m-text13 t-center">
    Categoria <%= @category.name %>
  </p>
</section>

<!-- Content page -->
<section class="bgwhite p-t-55 p-b-65">
  <div class="container">
    <div class="row">
      <!-- Left_bar -->
      <%= render "commun/left_bar"%>

      <div class="col-sm-6 col-md-8 col-lg-9 p-b-50">
        <!--  -->

        <!-- Product -->
        <div class="row">
          <!-- Card Product -->
          <%= render partial: "commun/card_product", locals: { products: @products } %>
        </div>
        <!-- Pagination -->
        <div class="row text-center">
          <div class="col-6 col-md-3 p-b-30 m-l-r-auto">
            <div class="d-flex justify-content-center">
              <%== pagy_bootstrap_nav(@pagy) %>
            </div>
          </div>
        </div>
      </div>
    </div>
  </div>
</section>

<!-- Footer -->
<%= render "commun/footer"%>

<!-- Whatsapp to top -->
<div class="whatsapp bg0-hov">
  <span class="symbol-btn-back-to-top">
    <%= link_to "", "https://api.whatsapp.com/send?phone=593978973576", class:"fa fa-whatsapp whatsapp-icon", alt:"WhatsApp", target: "_blank" %>
  </span>
</div>

app/views/commun/_card_product.html.erb
<% @products.each do |product| %>
  <div class="col-6 col-md-3 p-b-30 m-l-r-auto">
    <%= link_to product_path(product) do %>
      <!-- Block2 -->
      <div class="block2">
        <div class="block2-img wrap-pic-w of-hidden pos-relative <%= 'block2-labelsale' if product.offer %> ">
          <%= image_tag(product.picture_1.url(:thumbnail), :quality=>70, :class=>"block3-img dis-block") %>
          <%# <div class="block2-overlay trans-0-4">
            <a href="#" class="block2-btn-addwishlist hov-pointer trans-0-4">
              <i class="icon-wishlist icon_heart_alt" aria-hidden="true"></i>
              <i class="icon-wishlist icon_heart dis-none" aria-hidden="true"></i>
            </a>
            <div class="block2-btn-addcart w-size1 trans-0-4">
              <!-- Button -->
              <button class="flex-c-m size1 bg4 bo-rad-23 hov1 s-text1 trans-0-4">
                Obtener
              </button>
            </div>
          </div> %>
        </div>
        <div class="block2-txt p-t-20">
          <p class="block2-name dis-block s-text3 p-b-5">
            <%= product.name %>
          </p>
          <% if product.offer %>
            <span class="block2-newprice m-text8 p-r-5">
              $<%= product.price_offer %>
            </span>
          <% end %>
          <span class="block2-price m-text6 p-r-5 <%= 'block2-oldprice m-text7 p-r-5' if product.offer %>">
            $<%= product.price_base %>
          </span><br/>
          <span class="s-text6">Por:</span> <span class="s-text7"><%= product.provider.first_name %> <%= product.provider.last_name %></span>
        </div>
      </div>
    <% end %>
  </div>
<% end %>

app/views/commun/_category.html.erb
<!-- Categorias -->
<section class="blog bgwhite p-t-50 p-b-50">
  <div class="container">
    <div class="sec-title p-b-52">
      <h3 class="m-text5 t-center">
        Categorias
      </h3>
    </div>
    <div class="row text-center">
      <% @categories.each do |category| %>
        <div class="col-6 col-md-3 p-b-30 m-l-r-auto">
          <%= link_to category_path(category) do %>
            <div class="block3">
              <%# <%= link_to image_tag(category.image.url(:thumbnail)), category_path(category), class:"block3-img dis-block" %>
              <div class="block3-txt p-t-14">
                <h4 class="p-b-7">
                  <p class="m-text11">
                    <%= category.name %>
                  </p>
                </h4>
                <p class="s-text8">
                  <%= category.description %>
                </p>
              </div>
            </div>
          <% end %>
        </div>
      <% end %>
    </div>
  </div>
</section>

app/views/commun/_footer.html.erb
<!-- Footer -->
<footer class="bg6 p-t-45 p-b-43 p-l-45 p-r-45">
  <div class="flex-w p-b-10">
    <div class="w-size6 p-t-30 p-l-15 p-r-15 respon3">
      <h4 class="s-text12 p-b-30">CONTACTANOS</h4>
      <div>
        <p class="s-text7 w-size27">
          Francisco de Miranda N48-200 y Nicolás López. Quito - Ecuador
        </p>
        <div class="flex-m">
          <a href="#" class="fs-18 color1 p-r-20 fa fa-facebook"></a>
          <a href="#" class="fs-18 color1 p-r-20 fa fa-instagram"></a>
          <%= link_to "", "https://api.whatsapp.com/send?phone=978973576", class:"fs-18 color1 p-r-20 fa fa-whatsapp", alt:"WhatsApp", target: "_blank" %>
          <p class="s-text7 w-size27">Ecuador (+593)978973576</p>
        </div>
      </div>
    </div>

    <div class="w-size7 p-t-30 p-l-15 p-r-15 respon4">
      <h4 class="s-text12 p-b-30">
        Menu
      </h4>

      <ul>
        <li class="<%= 'sale-noti' if current_page?(products_path) %> p-b-9"><%= link_to 'Productos', products_path %></li>
        <li class="<%= 'sale-noti' if current_page?(offers_path) %> p-b-9"><%= link_to 'Ofertas', offers_path %></li>
        <li class="<%= 'sale-noti' if current_page?(about_index_path) %> p-b-9"><%= link_to 'Quienes somos', about_index_path %></li>
      </ul>
    </div>




    <div class="w-size8 p-t-30 p-l-15 p-r-15 respon3">
      <h4 class="s-text12 p-b-30">
        Metodo de pago
      </h4>

      <div class="s-text8">
        Contra entrega.
      </div>
      <div class="s-text8">
        Transferencias.
      </div>
      <div class="s-text8">
        Criptomonedas (Bitcoin)
      </div>

      <h4 class="s-text12 p-t-20">
        Proximamente
      </h4>

      <div class="p-t-9 p-r-15">
        <a href="#">
          <img class="h-size2" src="images/icons/paypal.png" alt="IMG-PAYPAL">
        </a>

        <a href="#">
          <img class="h-size2" src="images/icons/visa.png" alt="IMG-VISA">
        </a>

        <a href="#">
          <img class="h-size2" src="images/icons/mastercard.png" alt="IMG-MASTERCARD">
        </a>

        <a href="#">
          <img class="h-size2" src="images/icons/express.png" alt="IMG-EXPRESS">
        </a>

        <a href="#">
          <img class="h-size2" src="images/icons/discover.png" alt="IMG-DISCOVER">
        </a>
      </div>
    </div>

  </div>
  <div class="t-center p-l-15 p-r-15">
    <div class="t-center s-text8 p-t-20">
      Copyright © <%= DateTime.now.strftime('%Y') %> Todos los Derechos Reservados. | Tienda Nativa <i class="fa fa-heart-o" aria-hidden="true"></i> por <a href="http://www.technologynic.com/nic" target="_blank">Technology NIC</a>
    </div>
  </div>

</footer>

app/views/commun/_header.html.erb
<!-- Header -->
<header class="header1">
  <!-- Header desktop -->
  <div class="container-menu-header">
    <div class="topbar">
      <div class="topbar-social">
        <a href="#" class="topbar-social-item fa fa-facebook"></a>
        <a href="#" class="topbar-social-item fa fa-instagram"></a>
      </div>
      <span class="topbar-child1">
        <%= link_to " Llámanos o Wasapéanos al +593 978973576", "https://api.whatsapp.com/send?phone=593978973576", class:"topbar-social-item fa fa-whatsapp", alt:"WhatsApp", target: "_blank" %>
      </span>
      <div class="topbar-child2">
        <span class="topbar-email">
          info@tiendanativa.com
        </span>
      </div>
    </div>
    <div class="wrap_header_container">
      <!-- Logo -->
      <div class="logo_container">
        <a class="logo_img" href="/">
          <img src="images/logo.jpg" width="20%" alt="TIENDA NATIVA">
        </a>
      </div>
      <!-- Menu -->
      <div class="wrap_menu">
        <nav class="menu">
          <ul class="main_menu">
            <li class="<%= 'sale-noti' if current_page?(root_path) %>"><%= link_to 'Principal', '/' %></li>
            <li class="<%= 'sale-noti' if current_page?(products_path) %>"><%= link_to 'Productos', products_path %></li>
            <li class="<%= 'sale-noti' if current_page?(offers_path) %>"><%= link_to 'Ofertas', offers_path %></li>
            <li class="<%= 'sale-noti' if current_page?(about_index_path) %>"><%= link_to 'Quienes somos', about_index_path %></li>
          </ul>
        </nav>
      </div>
    </div>
  </div>

  <!-- Header Mobile -->
  <div class="wrap_header_mobile">
    <!-- Logo moblie -->
    <div class="logo-mobile">
      <a href="/">
        <img src="images/logo.jpg" width="70px" alt="TIENDA NATIVA">
      </a>
    </div>
    <!-- Button show menu -->
    <div class="btn-show-menu">
      <!-- Header Icon mobile -->
      <div class="btn-show-menu-mobile hamburger hamburger--squeeze">
        <span class="hamburger-box">
          <span class="hamburger-inner"></span>
        </span>
      </div>
    </div>
  </div>

  <!-- Menu Mobile -->
  <div class="wrap-side-menu" >
    <nav class="side-menu">
      <ul class="main-menu">
        <li class="item-topbar-mobile p-l-20 p-t-8 p-b-8">
          <span class="topbar-child1">
            <%= link_to " Llámanos o Wasapéanos al +593 978973576", "https://api.whatsapp.com/send?phone=593978973576", class:"fa fa-whatsapp", alt:"WhatsApp", target: "_blank" %>
          </span>
        </li>
        <li class="item-topbar-mobile p-l-10">
          <div class="topbar-social-mobile">
            <a href="#" class="topbar-social-item fa fa-facebook"></a>
            <a href="#" class="topbar-social-item fa fa-instagram"></a>
            <span class="topbar-email"><a href="#" class="topbar-social-item fa fa-envelope-open"> info@tiendanativa.com</a></span>          
          </div>
        </li>
        <li class="item-menu-mobile"><%= link_to 'Principal', '/' %></li>
        <li class="item-menu-mobile"><%= link_to 'Productos', products_path %></li>
        <li class="item-menu-mobile"><%= link_to 'Ofertas', offers_path %></li>
        <li class="item-menu-mobile"><%= link_to 'Quienes somos', about_index_path %></li>
      </ul>
    </nav>
  </div>
</header>

app/views/commun/_left_bar.html.erb
<div class="col-sm-6 col-md-4 col-lg-3 p-b-50">
	<div class="leftbar p-r-20 p-r-0-sm">
		<!--  -->
		<h4 class="m-text14 p-b-7">
			Categorias
		</h4>
		<ul class="p-b-54">
			<li class="p-t-4">
				<%= link_to 'Todos', products_path, class:"s-text13 active1" %>
			</li>
      <% @categories.each do |category| %>
        <li class="p-t-4">
          <%= link_to category.name, category_path(category), class:"s-text13" %>
        </li>
      <% end %>
		</ul>
	</div>
</div>

app/views/home/_product.html.erb
<!-- New Product -->
<section class="newproduct bgwhite p-t-45 p-b-105">
  <div class="container">
    <div class="sec-title p-b-52">
      <h3 class="m-text5 t-center">
        Productos
      </h3>
    </div>

    <!-- Slide2 -->
    <div class="row text-center">
      <%= render "commun/card_product" %>
    </div>

    <%# <div class="wrap-slick2">
      <div class="slick2">
      </div>
    </div> %>

    <!-- Pagination -->
    <div class="row text-center">
      <div class="col-6 col-md-3 p-b-30 m-l-r-auto">
        <div class="d-flex justify-content-center">
          <%== pagy_bootstrap_nav(@pagy) %>
        </div>
      </div>
    </div>

  </div>
</section>

app/views/home/index.html.erb
<!-- Header -->
<%= render "commun/header" %>
<!-- Category -->
<%= render partial: "commun/category", locals: { show: @categories } %>
<!-- Slide Main -->
<%= render "product" %>
<!-- Social -->
<%= render "social"%>
<!-- Footer -->
<%= render "commun/footer"%>

app/views/offers/index.html.erb
<% offers_path "Tienda nativa - Tienda online de productos artesanale hechos en Ecuador",
  "Encuentra todo tipo de artesania, ideal para ti y tu familia.",
  offers_path %>
<!-- Header -->
<%= render "commun/header" %>

<!-- Title Page -->
<section
  class="bg-title-page p-t-50 p-b-40 flex-col-c-m"
  style="background: linear-gradient(rgba(0,0,0,0.5), rgba(0,0,0,0.7)), url(images/heading-pages-02.jpg);
    background-repeat: no-repeat;
    background-size: cover;
    background-position: center center;
    color: #fff;
    text-align: center;">
  <h2 class="l-text2 t-center">
    Ofertas de producto.
  </h2>
</section>

<!-- Content page -->
<section class="bgwhite p-t-55 p-b-65">
  <div class="container">
    <div class="row">
      <!-- Left_bar -->
      <%= render "commun/left_bar"%>

      <div class="col-sm-6 col-md-8 col-lg-9 p-b-50">

        <!-- Product -->
        <div class="row">
          <!-- Card Product -->
          <%= render partial: "commun/card_product", locals: { products: @products } %>
        </div>

        <!-- Pagination -->
        <div class="row text-center">
          <div class="col-6 col-md-3 p-b-30 m-l-r-auto">
            <div class="d-flex justify-content-center">
              <%== pagy_bootstrap_nav(@pagy) %>
            </div>
          </div>
        </div>
      </div>
    </div>
  </div>
</section>

<!-- Footer -->
<%= render "commun/footer"%>

app/views/products/index.html.erb
<% products_path "Autoctono - Tienda online de productos artesanale hechos en Ecuador",
  "Encuentra todo tipo de artesania, ideal para ti y tu familia.",
  products_path %>
<!-- Header -->
<%= render "commun/header" %>

<!-- Title Page -->
<section
  class="bg-title-page p-t-50 p-b-40 flex-col-c-m"
  style="background: linear-gradient(rgba(0,0,0,0.5), rgba(0,0,0,0.7)), url(images/heading-pages-02.jpg);
        background-repeat: no-repeat;
        background-size: cover;
        background-position: center center;
        color: #fff;
        text-align: center;">
  <h2 class="l-text2 t-center">
    Producto en Ecuador.
  </h2>
  <%# <p class="m-text13 t-center">
    Nuevos productos en Ecuador. Colección 2018-2019
  </p> %>
</section>

<!-- Content page -->
<section class="bgwhite p-t-55 p-b-65">
  <div class="container">
    <div class="row">
      <!-- Left_bar -->
      <%= render "commun/left_bar"%>

      <div class="col-sm-6 col-md-8 col-lg-9 p-b-50">
        <!--  -->

        <!-- Product -->
        <div class="row">
          <!-- Card Product -->
          <%= render partial: "commun/card_product", locals: { products: @products } %>
        </div>
        <!-- Pagination -->
        <div class="row text-center">
          <div class="col-6 col-md-3 p-b-30 m-l-r-auto">
            <div class="d-flex justify-content-center">
              <%== pagy_bootstrap_nav(@pagy) %>
            </div>
          </div>
        </div>

      </div>
    </div>
  </div>
</section>

<!-- Footer -->
<%= render "commun/footer"%>

app/views/products/show.html.erb
<!-- Header -->
<%= render "commun/header" %>
<%= render partial: "layouts/breadcrumb", locals: { header_list: [{ :name => "Productos", :path => products_path }, { :name => @product.name }]} %>

<!-- Product Detail -->
<div class="container bgwhite p-t-35 p-b-80">
  <div class="flex-w flex-sb">
    <div class="w-size13 p-t-30 respon5">
      <div class="wrap-slick3 flex-sb flex-w">
        <div class="wrap-slick3-dots"></div>
        <div class="slick3">
          <% images = set_images(@product.picture_1, @product.picture_2, @product.picture_3) %>
          <% images.each do |image| %>
            <div class="item-slick3" data-thumb="<%= asset_path(image) %>">
              <div class="wrap-pic-w">
                <%= cl_image_tag asset_url(image), :alt => "" %>  
              </div>
            </div>
          <% end %>
        </div>
      </div>
    </div>

    <div class="w-size14 p-t-30 respon5">
      <h4 class="product-detail-name m-text16 p-b-13">
        <%= @product.name %>
      </h4>

      <% if @product.offer %>
        <span class="block2-newprice m-text8 p-r-5 size">
          $<%= @product.price_offer %>
        </span>
      <% end %>
      <span class="block2-price m-text17 p-r-5 <%= 'block2-oldprice m-text7 p-r-5' if @product.offer %>">
        $<%= @product.price_base %>
      </span><br/>

      <!--  -->
      <div class="p-t-33 p-b-60">
        <div class="flex-r-m flex-w p-t-10">
          <div class="flex-m flex-w">
            <div class="btn-addcart-product-detail size15 trans-0-4 m-t-10 m-b-10">
              <!-- Button -->
              <%= link_to "ORDENAR", "#my-modal-buy", :class => "flex-c-m sizefull bg1 bo-rad-23 hov1 s-text1 trans-0-4 m-l-10 m-r-10", "data-toggle" => "modal" %>
            </div>
          </div>
        </div>
      </div>

      <!--  -->
      <div class="wrap-dropdown-content bo6 p-t-15 p-b-14 active-dropdown-content">
        <h5 class="js-toggle-dropdown-content flex-sb-m cs-pointer m-text19 color0-hov trans-0-4">
          Descripción Adicional
          <i class="down-mark fs-12 color1 fa fa-minus dis-none" aria-hidden="true"></i>
          <i class="up-mark fs-12 color1 fa fa-plus" aria-hidden="true"></i>
        </h5>
        <div class="dropdown-content dis-none p-t-15 p-b-23">
          <p class="s-text8">
            <span class="s-text8 m-r-35">Por: <%= @product.provider.first_name %> <%= @product.provider.last_name %></span>
            <span class="s-text8 m-r-35">Categora: <%= @product.category.name %> </span>
            <span class="s-text8">En: <%= @product.city.name %> </span>
          </p>
          <p class="s-text8 p-t-10">
            <%= @product.description %>
          </p>
        </div>
      </div>
    </div>
  </div>
</div>

<!-- Footer @product -->
<%= render "commun/footer"%>

<div class="modal hide fade m-t-5" id="my-modal-buy" title="Form Buy" tabindex="-1" role="dialog">
  <div class="modal-dialog" role="document">
    <div class="modal-content">
      <div class="modal-header">
        <h5 class="modal-title">Quieres comprar: <%= @product.name%></h5>
      </div>
      <div class="modal-body">
        <p>Hola, déjanos tus datos al <b>CREAR PEDIDO</b>, un asesor se contactará contigo para realizar y finalizar tu orden.</p>
        <% url = "https://wa.me/593978973576?text=%C2%A1Hola!%20Quiero%20comprar%20" %>
        <% p = @product %>
        <%= form_tag(url + p.name, method: "get") do |f| %>
          <div class="modal-footer">
            <button type="button" class="flex-c-m sizefull bg1 bo-rad-23 hov1 s-text1 trans-0-4 m-l-10 m-r-10" data-dismiss="modal">Cancelar</button>
            <%pId = products_path + "/" + p.id.to_s%>
            <%= link_to "CREAR PEDIDO", url + p.name + " https://www.natienda.com" + pId, class:"flex-c-m sizefull bg1 bo-rad-23 hov1 s-text1 trans-0-4 m-l-10 m-r-10", target: "_black" %>
          </div>
        <% end %>
      </div>
    </div>
  </div>
</div>